const sensors=[
{id:'motion-bedroom',type:'ДАТЧИК ДВИЖЕНИЯ',name:'Движение · Спальня',desc:'Отслеживает присутствие в спальне и управляет ночным освещением.',ip:'192.168.1.101',signal:'−48 dBm',battery:'78%',protocol:'Zigbee 3.0',x:330,y:91,kind:'motion',icon:'◆'},
{id:'smoke-bedroom',type:'ДАТЧИК ДЫМА',name:'Дым · Спальня',desc:'Анализирует концентрацию дыма и мгновенно отправляет тревожное уведомление.',ip:'192.168.1.102',signal:'−51 dBm',battery:'92%',protocol:'Z-Wave',x:245,y:245,kind:'smoke',icon:'ϟ'},
{id:'door-bedroom',type:'ДАТЧИК ОТКРЫТИЯ',name:'Дверь · Спальня',desc:'Фиксирует открытие межкомнатной двери и участвует в сценариях климата.',ip:'192.168.1.103',signal:'−46 dBm',battery:'71%',protocol:'Zigbee 3.0',x:116,y:336,kind:'door',icon:'═'},
{id:'motion-living',type:'ДАТЧИК ДВИЖЕНИЯ',name:'Движение · Гостиная',desc:'Контролирует активность в общей зоне и запускает сценарии освещения.',ip:'192.168.1.104',signal:'−42 dBm',battery:'86%',protocol:'Zigbee 3.0',x:618,y:342,kind:'motion',icon:'◆'},
{id:'smoke-kitchen',type:'ДАТЧИК ДЫМА',name:'Дым · Кухня',desc:'Контролирует воздух возле зоны приготовления пищи с фильтрацией пара.',ip:'192.168.1.105',signal:'−39 dBm',battery:'95%',protocol:'Z-Wave',x:565,y:236,kind:'smoke',icon:'ϟ'},
{id:'motion-bath',type:'ДАТЧИК ДВИЖЕНИЯ',name:'Движение · Ванная',desc:'Включает мягкую подсветку и фиксирует присутствие в ванной комнате.',ip:'192.168.1.106',signal:'−55 dBm',battery:'64%',protocol:'Zigbee 3.0',x:430,y:510,kind:'motion',icon:'◆'},
{id:'door-entry',type:'ДАТЧИК ОТКРЫТИЯ',name:'Входная дверь',desc:'Контролирует главный вход. При охране любое открытие запускает тревогу.',ip:'192.168.1.107',signal:'−44 dBm',battery:'83%',protocol:'LoRaWAN',x:142,y:558,kind:'door',icon:'═'}];
const $=s=>document.querySelector(s),layer=$('#sensorLayer');let selected=sensors[3];
sensors.forEach(s=>{const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('class',`sensor ${s.kind}${s.id===selected.id?' selected':''}`);g.setAttribute('transform',`translate(${s.x} ${s.y})`);g.dataset.id=s.id;g.innerHTML=`<circle class="halo" r="24"/><circle class="core" r="15"/><text y="1">${s.icon}</text>`;g.onclick=()=>select(s);g.onmouseenter=e=>tip(e,s);g.onmouseleave=()=>$('#tooltip').hidden=true;layer.append(g)});
function select(s){selected=s;document.querySelectorAll('.sensor').forEach(el=>el.classList.toggle('selected',el.dataset.id===s.id));$('#dType').textContent=s.type;$('#dName').textContent=s.name;$('#dDesc').textContent=s.desc;$('#dIp').textContent=s.ip;$('#dSignal').textContent=s.signal;$('#dBattery').textContent=s.battery;$('#dProtocol').textContent=s.protocol;$('#dIcon').textContent=s.icon;$('#deviceToggle').checked=!$(`[data-id="${s.id}"]`).classList.contains('disabled');if(innerWidth<680)$('.details').scrollIntoView({behavior:'smooth'})}
function tip(e,s){const t=$('#tooltip'),w=$('.map-wrap').getBoundingClientRect(),r=e.currentTarget.getBoundingClientRect();t.textContent=s.name;t.hidden=false;t.style.left=`${r.left-w.left+r.width/2+8}px`;t.style.top=`${r.top-w.top}px`}
function notify(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
$('#deviceToggle').onchange=e=>{const node=$(`[data-id="${selected.id}"]`);node.classList.toggle('disabled',!e.target.checked);$('#online').textContent=document.querySelectorAll('.sensor:not(.disabled)').length;notify(e.target.checked?'Датчик включён':'Датчик временно отключён')};
document.querySelectorAll('.modes button').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.modes button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$('#mode').textContent=btn.textContent;notify(`Режим «${btn.textContent}» активирован`)});
$('#test').onclick=e=>{e.target.disabled=true;e.target.textContent='Проверка соединения…';setTimeout(()=>{e.target.disabled=false;e.target.textContent='Запустить проверку устройства';notify(`${selected.name}: устройство отвечает`)},1000)};
$('#clear').onclick=()=>{$('#eventList').innerHTML='<p style="color:#75857f;font-size:10px;text-align:center;padding:28px">Журнал событий очищен</p>';notify('Журнал очищен')};
function tick(){$('#clock').textContent=new Date().toLocaleTimeString('ru-RU')}setInterval(tick,1000);
